server:
    port: 9001
    servlet:
        context-path: /meiman
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/meiman_wallet?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    servlet:
        multipart:
            max-file-size: 3MB
            max-request-size: 3MB
mybatis:
    typeAliasesPackage: com.meiman.meimanwallet
    mapperLocations: classpath:mapper/*.xml
