spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://github.com/lblxxy/springCloud-configServer.git
          search-paths: config
          username:
          password:
      label: master
server:
  port: 8768