spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: https://gitee.com/lblxxy/springCloudDemo
          search-paths: springcloud/config
          username:
          password:
      label: dev
server:
  port: 8888