spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          配置git仓库地址
          uri: https://github.com/lblxxy/springCloud-configServer.git
#            配置仓库路径,不包含项目名
          search-paths: config
#          访问git仓库的用户名、密码。公开的话就不需要
          username:
          password:
#          配置仓库的分支
      label: master
server:
  port: 6066
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka/